apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-register-deployment
  labels:
    app: medical-register
spec:
  replicas: 2 # Adjust replica count as needed
  selector:
    matchLabels:
      app: medical-register
  template:
    metadata:
      labels:
        app: medical-register
    spec:
      containers:
        - name: medical-register
          image: medical-register-app:local # Use the locally built image
          imagePullPolicy: IfNotPresent # Important for local images not in a registry
          ports:
            - containerPort: 8080
          # Assuming Spring Boot Actuator is available for health checks
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 60 # Give Spring Boot more time to start
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 90 # Give Spring Boot more time to be fully up
            periodSeconds: 15
            failureThreshold: 3
          env:
            # SPRING_PROFILES_ACTIVE is set to 'prod' in the Dockerfile
            # Add environment variables required by application-prod.properties
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_CLIENT_SECRET
            - name: AUTH0_ISSUER_URI
              valueFrom:
                secretKeyRef:
                  name: auth0-credentials
                  key: AUTH0_ISSUER_URI
            # APP_BASE_URL should be the URL you use to access the app locally
            # For LoadBalancer service type in Docker Desktop, this is often http://localhost:PORT
            - name: APP_BASE_URL
              value: "http://localhost:80" # Matches the Service port
            # Optional: If you need to override the H2 password default in prod properties
            # - name: H2_DB_PASSWORD
            #   value: "your_h2_password"

          resources:
            # Define resource requests and limits as appropriate for your application
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
