apiVersion: v1
kind: Service
metadata:
  name: medical-register-service
  labels:
    app: medical-register
spec:
  type: LoadBalancer # Or ClusterIP if you're using an Ingress controller
  selector:
    app: medical-register # Matches the labels of the Pods in the Deployment
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the Service
      targetPort: 8080 # Port on the Pods/Containers